SELECT l.id, l.START_DATE, l.END_DATE, l.TOTAL, (cu.NAME || ' ' || cu.LASTNAME) AS "CUSTOMER NAME", ca.NAME AS 'CAR NAME', e.NAME AS "EMPLOYEE NAME" FROM LOCATIONS AS l
INNER JOIN CARS AS ca
ON l.CAR_ID = ca.ID
INNER JOIN EMPLOYEES AS e
ON l.EMPLOYEE_ID = e.ID
INNER JOIN CUSTOMERS AS cu
ON l.CUSTOMER_ID = cu.ID;